name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare:
    name: Prepare Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'
          #extensions: mbstring, sqlite, pdo_sqlite, bcmath
          #coverage: none

      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Dependencies
        run: |
          composer install \
            --no-scripts \
            --no-ansi \
            --no-interaction \
            --no-progress \
            --prefer-dist

      - name: Prepare .env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      # Export vendor/
      - name: Upload vendor artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor

      # Export the source code
      - name: Upload source artifact
        uses: actions/upload-artifact@v4
        with:
          name: source
          path: .
          retention-days: 1

  # ---------------------------------------------------------
  # LINT â†’ Laravel Pint
  # ---------------------------------------------------------
  qa:
    name: QA -  Lint & Static Analysis
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Download source
        uses: actions/download-artifact@v4
        with:
          name: source

      - name: Download vendor
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Laravel Pint
        run: php vendor/bin/pint --test

      - name: PHPStan
        run: php vendor/bin/phpstan analyse --memory-limit=256M

  tests:
    name: Test Suites
    runs-on: ubuntu-latest
    needs: prepare
    #needs: [prepare, qa]

    steps:
      - name: Download source
        uses: actions/download-artifact@v4
        with:
          name: source

      - name: Download vendor
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: sqlite, pdo_sqlite

      - name: Setup SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      #- name: Tests
      #  run: php artisan test --coverage --min=30

      - name: Unit Tests
        run: php artisan test --coverage --min=20 --testsuite=Unit

      - name: Integration Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test  --coverage --min=50 --testsuite=Integration

      - name: Feature Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test  --coverage --min=10 --testsuite=Feature


