name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main
    conclusion: success

jobs:
  # ===============================
  # 1️⃣ Deploy para DEV
  # ===============================
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DEV
        run: |
          echo "Deploying image to DEV..."
          sleep 5
          echo "DEV deployed successfully!"

  # ===============================
  # 2️⃣ Deploy para PROD
  # ===============================
  deploy_prod:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PROD
        run: |
          echo "Deploying image to PROD..."
          sleep 5
          echo "PROD deployed successfully!"
